name: Generate Pacman Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: codingwithrahul
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push to Output Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git checkout -B output
          git add .
          git commit -m "Update Pacman Graph" || echo "No changes"
          git push origin output --force
